<nav class="adminNav">
    <ul>
        <li>
            <a href="/Projet_Accou-ferme/adminDisplayOrders">Voir les commandes</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminProducts">Gérer les produits</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminNews">Gérer les actus</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminMedias">Gérer les photos</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminContacts">Voir les messages</a>
        </li>
        <li>
            <a class="disconnet button" href="/Projet_Accou-ferme/adminDisconnect">
                <span class="bi-power"></span> Me déconnecter
            </a>
        </li>
    </ul>
</nav>
