<nav class="adminNav">
    <ul>
        <li>
            <a href="/Projet_Accou-ferme/adminDisplayOrders" title="Voir les commandes">Voir les commandes</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminProducts" title="Gérer les produits">Gérer les produits</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminNews" title="Gérer les actus">Gérer les actus</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminMedias" title="Gérer les photos">Gérer les photos</a>
        </li>
        <li>
            <a href="/Projet_Accou-ferme/adminContacts" title="Voir les messages">Voir les messages</a>
        </li>
        <li>
            <a class="disconnet button" href="/Projet_Accou-ferme/adminDisconnect" title="Se déconnecter">
                <span class="bi-power"></span> Me déconnecter
            </a>
        </li>
    </ul>
</nav>
