<nav class="adminNav">
    <ul>
        <li><a href="/Projet_Accou-ferme/adminDisplayOrders">Voir les commandes</a></li>
        <li><a href="/Projet_Accou-ferme/adminProducts">Gérer les produits</a></li>
        <li><a href="/Projet_Accou-ferme/adminOrders">Gérer les commandes</a></li>
        <li><a href="/Projet_Accou-ferme/adminNews">Gérer les actus</a></li>
        <li><a href="/Projet_Accou-ferme/adminMedias">Gérer les photos</a></li>
    </ul>
</nav>
