<footer class="footer">
    
    <p>@ Accou'ferme - Création du site <a href="https://github.com/Marine-Sanson">Marine Sanson</a></p>
    
    <nav class="footerNav">
        <ul>
            <li class="containerLogoFooter">
                <h2 class="sr-only">Accou ferme</h2>
                <a href="/Projet_Accou-ferme/" title="Accueil">
                    <figure class="logoImg">
                        <?php
                        if(isset($data["newsDetail"]) && ($data["newsDetail"]->getId()) !== null)
                        {
                        ?>
                        <img src="../assets/img/logo-arbre-oreille-512.png" alt="logo Accou'ferme">
                        <?php
                        }
                        else
                        {
                        ?>
                        <img src="./assets/img/logo-arbre-oreille-512.png" alt="logo Accou'ferme">
                        <?php
                        }
                        ?>
                    </figure>
                </a>
                <a id="homeLink" href="/Projet_Accou-ferme/" title="Accueil">Accueil</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/mentions-legales" title="Mentions légales">Mentions légales</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/contact" title="Contact">Contact</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/a-propos" title="Qui suis-je?">Qui suis-je?</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/galerie" title="Galerie">Galerie</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/produits" title="Produits">Produits</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/commandes" title="Commandes">Commandes</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/actus" title="Actus et Recettes">Actus et Recettes</a>
            </li>
            <li class="cssValid">
                <a href="https://jigsaw.w3.org/css-validator/check/referer">
                    <img src="https://jigsaw.w3.org/css-validator/images/vcss"
                         alt="CSS Valide !">
                </a>
            </li>
        </ul>
    </nav>

    <p>
    </p>
            
</footer>

<?php

if ($template === "products")
{
?>
    <script type="module" src="/Projet_Accou-ferme/assets/javascript/products/index.js"></script>
<?php
}
else if($template === "basket")
{
?>
    <script type="module" src="/Projet_Accou-ferme/assets/javascript/basket/index.js"></script>
<?php
}
else if($template === "news")
{
?>
    <script type="module" src="/Projet_Accou-ferme/assets/javascript/news/index.js"></script>
<?php
}
else
{
?>
    <script type="module" src="/Projet_Accou-ferme/assets/javascript/header/index.js"></script>
<?php
}
?>