<!-- ---------- TOOLBAR ---------- -->
        <div class="toolbar">
    	    <div class="innerToolbar">  
                <div class="logoHeader" >
                    <div class="logoImg">
                        <img src="./assets/img/logo.png" alt="logo Accou'ferme" />
                    </div>
                    <h1><a>Accou'ferme</a></h1>
                </div>
                <nav class="menu" id="menu">
                    <ul>
                        <li><a href="/Projet_Accou-ferme">Accueil</a></li>
                		<li><a href="/Projet_Accou-ferme/about">Qui suis-je?</a></li>
                		<li><a href="/Projet_Accou-ferme/gallery">Galerie photos</a></li>
                		<li><a href="/Projet_Accou-ferme/produce">Produits</a></li>
                		<li><a href="/Projet_Accou-ferme/basket">Réservation de paniers</a></li>
                		<li><a href="/Projet_Accou-ferme/news">Actus et Recettes</a></li>
                		<li><a href="/Projet_Accou-ferme/contact">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>

<header>
    
    
        
</header>