<header>
    <a class="sr-only" href="#main-title">Accéder directement au contenu</a>
    <button id="mobile-header-button">
        <span class="bi-list"></span>
        <span class="sr-only">Ouvrir le menu</span>
    </button>
    <nav id="main-nav">
        <ul>
            <li id="containerLogoHeader">
                <h2 class="sr-only">Accou ferme</h2>
                <a href="/Projet_Accou-ferme/" title="Accueil">
                    <figure id="logoImgHeader">
                        <?php
                        if(isset($data["newsDetail"]) && ($data["newsDetail"]->getId()) !== null)
                        {
                        ?>
                        <img src="../assets/img/logo-arbre-oreille-512.png" alt="logo Accou'ferme">
                        <?php
                        }
                        else
                        {
                        ?>
                        <img src="./assets/img/logo-arbre-oreille-512.png" alt="logo Accou'ferme">
                        <?php
                        }
                        ?>
                    </figure>
                </a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/a-propos" title="Qui suis-je?">Qui suis-je?</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/galerie" title="Galerie">Galerie</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/produits" title="Produits">Produits</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/commandes" title="Commandes">Commandes</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/actus" title="Actus et Recettes">Actus et Recettes</a>
            </li>
            <li>
                <a href="/Projet_Accou-ferme/contact" title="Contact">Contact</a>
            </li>
        </ul>
    </nav>
</header>


