<section id="order">
    
    <h2>Passer commande</h2>
    
    <section id="orderDetail">
        <form id="orderForm" action="/Projet_Accou-ferme/_validationOrder" method="POST"> 

            <?php 
            $orderVarieties = $data["order"];
            foreach($orderVarieties["items"] as $key => $orderVariety)
            {
            ?>
                
                <fieldset class="orderVariety">
                    <h3 class="orderVarietyH3">Variété : <?= $orderVariety["variety"] ?>
                    </h3>
                    <input id="variety-name-<?= $orderVariety["variety"] ?>" type="hidden" name="variety-<?= $orderVariety["variety"] ?>" value="<?= $orderVariety["variety"] ?>" />
                    
                    <p class="orderVarietyP1">prix <?= $orderVariety["price"] ?> €</p>
                    <input id="variety-price-<?= $orderVariety["variety"] ?>" type="hidden" name="price-<?= $orderVariety["variety"] ?>" value="<?= $orderVariety["price"] ?>" />
    
                    <p class="orderVarietyP2">par <?= trim($orderVariety["units"], "(s)") ?></p>
                    <input id="variety-units-<?= $orderVariety["variety"] ?>" type="hidden" name="units-<?= $orderVariety["variety"] ?>" value="<?= $orderVariety["units"] ?>" />
    
                    <p class="orderVarietyP3">Quantité : <?= $orderVariety["amount"] ?></p>
                    <input id="variety-amount-<?= $orderVariety["variety"] ?>" type="hidden" name="amount-<?= $orderVariety["variety"] ?>" value="<?= $orderVariety["amount"] ?>" />
    
                    <p class="orderVarietyP4">soit : <?= ($orderVariety["totalVariety"]) ?> €</p>
                    <input id="variety-totalVariety-<?= $orderVariety["variety"] ?>" type="hidden" name="totalVariety-<?= $orderVariety["variety"] ?>" value="<?= $orderVariety["totalVariety"] ?>" />
    
                </fieldset>
            <?php
            }
            ?>

            <fieldset class="total">
                <a class="totalReturn" href="basket">Continuer mes achats</a>
                <p class="totalP">Prix total : <?= $orderVarieties["totalPrice"] ?> €</p>
                <input id="variety-totalPrice-<?= $orderVarieties["totalPrice"] ?>" type="hidden" name="totalPrice" value="<?= $orderVarieties["totalPrice"] ?>" />
            </fieldset>
            <fieldset id="client">
                <label id="clientFirstNameLab" for="firstName">Entrez votre prénom </label>
                <input id="clientFirstNameIn" type="text" name="firstName" value="prenom" />
                <label id="clientNameLab" for="name">Entrez votre nom </label>
                <input id="clientNameIn" type="text" name="name" value="nom" />
                <label id="clientEmailLab" for="email">Entrez votre Email </label>
                <input id="clientEmailIn" type="email" name="email" value="email" />
                <label id="clientTelLab" for="tel">Entrez votre numéro de téléphone </label>
                <input id="clientTelIn" type="tel" name="tel" value="telephone" />
            </fieldset>
            <fieldset id="retrait">
                <p id="retraitP">Choisissez le jour de retrait :</p>
                <input id="retraitMercIn" class="radio" type="radio" id="mercredi" name="date_retrait" value="mercredi" >
                <label id="retraitMercLab" for="mercredi">Mercredi</label>
                <input id="retraitMarIn" class="radio" type="radio" id="samedi" name="date_retrait" value="mercredi" >
                <label id="retraitMarLab" for="samedi">Samedi</label>
            </fieldset>
            <fieldset id="orderSubmit">
                <input id="orderSubmitIn" type="submit" value="Valider la commande" />
            </fieldset>
            
        </form>
        
        
    </section>
    
</main>