<section id="order">
    
    <h2>Passer commande</h2>
    
    <section id="orderDetail">
        <form>
            <fieldset class="orderVariety">
                <h3>Variété : Noire de Crimée</h3>
                <p>prix 5 €</p>
                <p>par Kilo</p>
                <p>Quantité : 1</p>
                <p>soit : 10 €</p>
            </fieldset>
            <fieldset class="orderVariety">
                <h3>Variété : Charlotte</h3>
                <p>prix 4 €</p>
                <p>par Kilo</p>
                <p>Quantité : 2</p>
                <p>soit : 8 €</p>
            </fieldset>
            <fieldset class="orderVariety">
                <h3>Variété : Chou-Fleur</h3>
                <p>prix 3 €</p>
                <p>par Pièce</p>
                <p>Quantité : 2</p>
                <p>soit : 6 €</p>
            </fieldset>
            <fieldset class="total">
                <p>Prix total : 24 €</p>
            </fieldset>
            <fieldset class="email">
                <label for="email">Entrez votre Email</label>
                <input type="email" name="email" value="email" />
            </fieldset>
            <fieldset class="retrait">
                <p>Choisissez le jour de retrait :</p>
                <input class="radio" type="radio" id="mercredi" name="date_retrait" value="mercredi" >
                <label for="mercredi">Mercredi</label>
                <input class="radio" type="radio" id="samedi" name="date_retrait" value="mercredi" >
                <label for="samedi">Samedi</label>
            </fieldset>
            <fieldset>
                <input type="submit" value="Valider la commande" />
            </fieldset>
            
        </form>
        
        
    </section>
    
</main>