<section id="update" class="card">
    <header id="basketHeader">
        <h2>Mon panier</h2>
        <a class="button bi-x-octagon" href="commandes"><span class="desktop">  fermer</span></a>
    </header>
    <section id="updateContentSection">
        <ul id="updateContent">

        </ul>
    </section>
    <footer id="basketFooter">
        <p>Total : <span id="totalOrderPrice">25</span> €</p>
        <a class="button" id="totalOrderContinue" href="commandes">Continuer mes achats</a>
        <a class="button" id="totalOrderShowBasket" href="detail-commande">Voir mon panier</a>
    </footer>

</section>