<aside id="update">
    <header id="basketHeader">
        <h2>Mon panier</h2>
    </header>
    <main id="updateContentSection">
        <ul id="updateContent">

        </ul>
    </main>
    <footer id="basketFooter">
        <p>Total : <span id="totalOrderPrice">25</span> €</p>
        <a class="button" id="totalOrderContinue" href="commandes">Continuer mes achats</a>
        <a class="button" id="totalOrderShowBasket" href="detail-commande">Voir mon panier</a>
    </footer>

</aside>