<main id="about">
    
    <h1>Qui suis-je?</h1>
    
    <section id="aboutMain">
        
        <article id="aboutProjet">

            <figure id="aboutProjetFig">
                <img src="./assets/img/gallery/Stephane.jpg"
                     alt="photo Stéphane">
            </figure>

            <h2 id="aboutProjetTitle">Mon projet</h2>
            
            <section id="aboutProjetText">

                <p>Jusqu'en 2022, mon activité professionnelle était centrée sur l'accompagnement de travailleurs
                handicapés pour leur permettre de développer leurs propres compétences. Dans les dernières années, j'ai
                développé un atelier horticulture, mais le lien avec la nature, le développement de nouvelles cultures, de
                cultures de variétés anciennes étaient limité par les contraintes liées à l'établissement.</p>
                <p>Ainsi c'est tout naturellement que je me suis tourné vers une formation de maraicher pour me connecter
                plus profondément avec la nature, avoir le plaisir de voir germer les graines semées, de prendre en compte
                la diversité biologique, voir au quotidien les résultats de son travail et aussi partager.</p>
                <p>Ma reconversion professionnelle a aussi été guidée par l'envie de faire quelque chose qui ait du sens et
                aussi d'être son propre patron tout en s'inscrivant dans une démarche sociétale respectueuse de
                l'environnement et de l'humain.</p>
            
            </section>
        </article>

        <article id="aboutPhilo">

            <figure id="aboutPhiloFig">
                <img src="./assets/img/gallery/semis.jpg"
                     alt="photo de jeunes plants en godets">
            </figure>

            <h2 id="aboutPhiloTitle">Ma philosophie</h2>

            <section id="aboutPhiloText">

                <p>Le respect de la terre et de la nature est un des piliers de ma démarche et ainsi, la culture
                maraichère, de mon point de vue ne peut se faire que par l'utilisation d'engrais verts, de paillages
                et de cultures mixtes afin de ne pas utiliser les pesticides et autres molécules chimiques non naturelles.
                C'est pourquoi mon maraichage s'inscrit dans les principes de l'agriculture biologique.</p>
                <p>Un autre pilier de cette démarche est de montrer dans une certaine mesure la diversité du monde des
                légumes, voire de créer des légumes parfaits tant dans leur saveur que dans leur qualité nutritive.</p>
                <p>J'ai conscience qu'être maraicher permet de produire du lien et du sens dans la mesure où les circuits
                courts relient la production et la consommation. D'autre part, une approche pédagogique est essentielle
                pour favoriser les échanges avec les consommateurs. C'est également dans cet objectif que le projet d'une
                ferme pédagogique est en germination.</p>
            </section>
                
        </article>
    </section>
</main>