<main class="main">
    <section class="about">
        <h1>Qui suis-je?</h1>
        <img src="./assets/img/gallery/vache-min.jpg" alt="photo Stéphane"></img>
        <h2>Mon projet</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vero, rem, non, quo, quam ducimus officiis distinctio dolor beatae sapiente aspernatur molestias cupiditate ipsam eos facilis sed debitis minus. Distinctio, aperiam, nemo dignissimos dolorum asperiores iusto</p>
        <p>Veritatis ullam quisquam dolorem nulla qui nisi tempora eaque eum inventore eos facilis explicabo optio consequuntur adipisci impedit quae error iste nihil possimus! Accusamus, neque, cum, alias, maiores ipsum harum fugiat minus cupiditate ipsam ipsa recusandae aspernatur nisi nemo debitis inventore doloribus similique amet error natus omnis minima magnam provident voluptate necessitatibus in rerum dolores distinctio nulla laborum impedit.</p>
        <p>Accusantium, nostrum beatae provident possimus maiores reprehenderit necessitatibus delectus tempore voluptate exercitationem consequatur totam hic fugiat sequi natus soluta culpa similique. Saepe, repellendus assumenda iusto aliquam.</p>
        <h2>Ma philosophie</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, vel sint similique vero asperiores nobis in ex laudantium molestias veniam nesciunt possimus doloribus quibusdam aperiam repellat velit dolorum nisi eveniet consectetur necessitatibus nemo doloremque voluptas est explicabo quos! Saepe, voluptate porro distinctio harum laudantium omnis molestias nulla cupiditate beatae ratione quia veritatis nisi qui.</p>
        <p>Sunt, aliquam, aliquid eos iste vero sint natus voluptatum facilis ipsam deserunt optio ipsa voluptatibus eligendi recusandae praesentium numquam iure dignissimos ratione libero at. Maxime, repellendus, eos officia nobis sunt fugit nihil doloremque impedit suscipit minus architecto quisquam cumque quidem quae neque dolorem doloribus in expedita ab rem nesciunt ea eius qui.</p>
        <p>Aperiam saepe esse possimus nostrum impedit ex sunt magni repellendus nulla! Adipisci, voluptas, dolore sequi quaerat repellat ad possimus quasi dicta beatae sint deleniti excepturi soluta quibusdam esse ducimus consequuntur laborum blanditiis provident perspiciatis.</p>
        
    </section>
</main>