<main class="admin">
    
    <h1>Espace Admin</h1>
    
    <h2>Veuillez vous connecter</h2>
    
    <?php require "_messages.phtml"; ?>
    
    <form id="adminForm" action="/Projet_Accou-ferme/adminMenu" method="POST">
            
        <fieldset>
                
            <label for="username">Identifiant : </label>
            <input id="username" type="text" name="username">
            <label for="password">Mot de passe : </label>
            <input id="password" type="password" name="password">
            
            <button class="button" id="connectAdmin" type="submit">Valider</button>
            
        </fieldset>

    </form>

</main>