<main id="adminMedias">
    
    <?php require "_adminNav.phtml"; ?>

    <h1>Gestion des images</h1>
    <h2>Téléchargement d'images</h2>
    
    <?php require "_messages.phtml"; ?>
    
    <form id="uploader" action="/Projet_Accou-ferme/adminMedias" method="post" enctype="multipart/form-data">
        <p>Choisir une image à télécharger:</p>
        <input type="file" name="fileToUpload" id="fileToUpload">
        <label id="fileToUploadLabel" for="alt">Description de l'image :</label>
        <input type="text" name="alt" id="fileAlt">
        <input id="uploaderButton" class="button" type="submit" value="Upload Image" name="submit">
    </form>
    
    <h2>Suppression d'images</h2>
    
    <ul id="deleteNewsImg">
        <?php
        foreach($data["allMedias"] as $key => $media)
        {
        ?>
            <li class="deleteNewsImageLi" >
                <form class="deleteNewsImageForm" name="deleteImage" method="POST" action="/Projet_Accou-ferme/deleteImage">
                    <img src="<?= $media["url"]; ?>" alt=" <?= $media["alt"]; ?>">
                    <input type="hidden" name="mediaId" value=" <?= $media["id"] ?>">
                    <input class="deleteNewsImageButton button" type="submit" name="deleteImage" value="Supprimer cette image">
                </form>
            </li>
        <?php
        }
        ?>
    </ul>
    
</main>