<main id="adminDisplayOrders">

    <?php require "_adminNav.phtml"; ?>
    
    <h1>AdminDisplayOrders</h1>
    
    <h2>Voir les prochaines commandes</h2>
    
    <form class="choseOrders" method="POST" action="/Projet_Accou-ferme/adminDisplayOrdersByDay">

        <input type="radio" id="mardi" name="day" value="mardi">
        <label for="mardi">Mardi</label>
        <input type="radio" id="samedi" name="day" value="samedi">
        <label for="samedi">Samedi</label>
        
        <input type="submit" value="Valider"/>
    </form>
    
        
    <?php
    if(isset($_POST["day"]))
    {
        $allorders = $data;
        ?>
        <p class="choosenDay">commandes pour <?= $_POST["day"]; ?></p>
        
        <section id="displayOrders">
            <?php
            foreach($allorders as $key => $order)
            {
                foreach($order as $key => $orderDetail)
                {
                    if(isset($orderDetail["date_commande"]))
                    {
                    ?>
                        <article class="displayOrder">
                            <p>Date de commande : <?= $orderDetail["date_commande"]; ?></p>
                            <p>Id : <?= $orderDetail["id"]; ?></p>
                            <p><?= $orderDetail["name"]; ?> <?= $orderDetail["first_name"]; ?> <?= $orderDetail["email"]; ?> <?= $orderDetail["tel"]; ?>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Variété</th>
                                        <th>Quantité</th>
                                        <th>Unité</th>
                                        <th>Prix</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th colspan="4">Total commande : </th>
                                        <td><?= $orderDetail["total_price"]; ?> €</td>
                                    </tr>
                                    <tr>
                                        <td colspan="5" class="buttonTerminer">
                                            <form method="POST" action="/Projet_Accou-ferme/terminer">
                                                <input type="hidden" name="id" value ="<?= $orderDetail["id"]; ?>">
                                                <input class="button" type="submit" value="Terminer"/>
                                            </form>
                                        </td>
                                    </tr>
                                </tfoot>
                                <?php
                                $varieties = $allorders["varieties"];
                                foreach($varieties as $key => $varietyDetail)
                                {
                                ?>
                                    <tbody>
                                        <tr>
                                            <td><?= $varietyDetail["variety_name"]; ?></td>
                                            <td><?= $varietyDetail["amount"]; ?></td>
                                            <td><?= $varietyDetail["units"]; ?></td>
                                            <td><?= $varietyDetail["price"]; ?> €</td>
                                            <td><?= $varietyDetail["total_variety"]; ?> €</td>
                                        </tr>
                                    </tbody>
                                <?php
                                }
                                ?>
                            </table>
                        </article>
                    <?php
                    }
                    ?>
                <?php
                }
                ?>
            <?php
            }
            ?>
        </section>
    <?php
    }
    ?>
    
</main>