<main id="adminNews">
    
    <?php require "_adminNav.phtml"; ?>
    
    <h1>AdminNews</h1>
    
    <h2>Créer une catégorie</h2>
    
    <form class="adminCategoryForm" method="POST" action="/Projet_Accou-ferme/_categoryCreated">

        <label for="newCat">Créer une nouvelle catégorie</label>
        <input type="text" name="newCat" />
        <button id="createNewCat" type="submit">Valider</button>

    </form>
    
    <h2>Créer une news</h2>
    
    <form class="adminNewsForm" method="POST" action="/Projet_Accou-ferme/_newsCreated">
        <fieldset id="selectNewsCategory">
            <h2>Choisir une catégorie</h2>
            <?php
            foreach($data['categories'] as $key => $category){
        		?>
        		<input type="radio" value="<?= $category["id"]; ?>" name="cat" />
        		<label for="cat"><?=$category["name"]; ?></label> 
        		
        	<?php
            }
            ?>
        </fieldset>

        <fieldset>
            <label for="name">Titre</label>
            <input type="text" name="name"/>
            <label for="content">Contenu</label>
            <input type="textarea" name="content"/>
            <button id="submitNewNews" type="submit">Valider</button>
        </fieldset>
        
    </form>
    
    <h2>Mettre à jour une news</h2>
    
    <h2>supprimer une news</h2>
    
</main>