<main id="adminNews">
    
    <?php require "_adminNav.phtml"; ?>
    
    <h1>AdminNews</h1>
    
    <h2>Créer une catégorie</h2>
    
    <?php
    if(isset($data["errors"]) && $data["errors"] !=="")
    {
        foreach($data["errors"] as $key => $error)
        {
    ?>
        <p class="errors"> <?= $error ?></p>
    <?php
        }
    }
    else if(isset($data["validation"]))
    {
    ?>
        <p class="validation"> <?= $data["validation"] ?> </p>
    <?php
    }
    ?>
    
    <form class="adminCategoryForm" method="POST" action="/Projet_Accou-ferme/_categoryCreated">

        <label for="newCat">Créer une nouvelle catégorie</label>
        <input type="text" name="newCat" />
        <button id="createNewCat" type="submit">Valider</button>

    </form>
    
    <h2>Créer une news</h2>
    
    <form class="createNewsForm" method="POST" action="/Projet_Accou-ferme/adminCrudNews">
        <input type="hidden" name="action" value="create" />
        <input type="submit" value="Créer" />
    </form>

    <h2>Mettre à jour ou supprimer une news</h2>
    <ul>

        <?php
        foreach($data["allNews"] as $key => $singleNews)
        {
        ?>
        <li>
            <article class="udNews">
                <h3><?= $singleNews["name"] ?></h3>
                <form class="updateNewsForm" method="POST" action="/Projet_Accou-ferme/adminCrudNews">
                    <input type="hidden" name="action" value="update" />
                    <input type="hidden" name="crudId" value="<?= $singleNews["id"] ?>" />
                    <input type="submit" value="Modifier" />
                </form>
                <form class="deleteNewsForm" method="POST" action="/Projet_Accou-ferme/adminCrudNews">
                    <input type="hidden" name="action" value="delete" />
                    <input type="hidden" name="crudId" value="<?= $singleNews["id"] ?>" />
                    <input type="submit" value="Supprimer" data-news-id="<?= $singleNews["id"] ?>"/>
                </form>
            </article>
        </li>
        <?php
        }
        ?>

    </ul>

    

</main>