<main id="adminMenu">

<h1>adminMenu</h1>

<h2>Salut Stéphane, bienvenu dans ton espace</h2>

<nav>
    <ul>
        <li><a href="/Projet_Accou-ferme/adminDisplayOrders">Voir les commandes</a></li>
        <li><a href="/Projet_Accou-ferme/adminProducts">Gérer les produits</a></li>
        <li><a href="/Projet_Accou-ferme/adminNews">Gérer les actus</a></li>
        <li><a href="/Projet_Accou-ferme/adminMedias">Gérer les photos</a></li>
        <li><a href="/Projet_Accou-ferme/adminContacts">Voir les messages</a></li>
    </ul>
</nav>
    
</main>
