<main id="adminCrudVariety">
    
    <?php require "_adminNav.phtml"; ?>

    <?php
    if(isset($data["errors"]))
    {
    ?>
        <ul class="errors">
            <?php
            foreach($data["errors"] as $key => $error)
            {
            ?>
            <li> <?= $error ?> </li>
            <?php    
            }
            ?>
        </ul>
    <?php    
    }
    ?>
        
    <?php
    if(isset($data["variety"]) && !empty($data["variety"]))
    {
        $id = $data["variety"]->getId();
        $productId = $data["variety"]->getProductId();
        $name = $data["variety"]->getName();
        $seasonStart = $data["variety"]->getSeasonStart();
        $seasonEnd = $data["variety"]->getSeasonEnd();
        $description = $data["variety"]->getDescription();
        $mediaId = $data["variety"]->getMediaId();
        $availablity = $data["variety"]->getAvailablity();
        $offer = $data["variety"]->getOffer();
        $quantityAvailable = $data["variety"]->getQuantityAvailable();
        $units = $data["variety"]->getUnits();
        $price = $data["variety"]->getPrice();
        
        if(isset($media) && $media !== [])
        {
            $media = $data["media"];
            $mediaUrl = $media->getUrl();
            $mediaAlt = $media->getAlt();
        }
    }

    if($data["action"] === "create")
    {
    ?>
        <form id="varietyForm" name="varietyForm" method="POST" action="/Projet_Accou-ferme/adminCreateVariety">
    <?php
    }
    else if($data["action"] === "update")
    {

    ?>
        <form id="varietyForm" name="varietyForm" method="POST" action="/Projet_Accou-ferme/adminUpdateVariety">
    <?php
    }
    else if($data["action"] === "delete")
    {

    ?>
        <form id="varietyForm" name="varietyForm" method="POST" action="/Projet_Accou-ferme/adminDeleteVariety">
    <?php        
    }

    ?>
        <input type="hidden" name="id" 
        <?php

        if(isset($id))
        {
        ?>
            value="<?= $id ?>" 
        <?php
        }
        ?>
        >

        <select  id="selectProductsForm" class="selectProducts" name="productId">
            <option value = "0">Selectionner un produit</option>
            <?php
            
            foreach($data['allProducts'] as $key => $product)
            {
        	?>
        		<option value=" <?= $product["id"]; ?> "
        		<?php
                if(isset($productId) && $product["id"] === $productId)
                {
                ?>
                    selected
                <?php
                $idProduct = $product['id'];
                }
                ?>
                > <?=$product["name"]; ?>
        		</option>
        		<?php
            }
            ?>
        </select>

        <label id="varietyNameLabel" for="name">Nom :</label>  
        <input id="varietyNameInput" class="productName" type="text" name="name" 
        <?php
        if(isset($name))
        {
        ?>
            value="<?= $name ?>" 
        <?php
        }
        ?>
        >

        <label id="seasonStartLabel" for="seasonStart">Début de saison :</label>  
        <input id="seasonStartInput" class="productSeasonStart" type="text" name="seasonStart"
        <?php
        if(isset($seasonStart))
        {
        ?>
            value="<?= $seasonStart ?>" 
        <?php
        }
        ?>
        >
        
        <label id="seasonEndLabel" for="seasonEnd">Fin de saison :</label>  
        <input id="seasonEndInput" class="productSeasonEnd" type="text" name="seasonEnd"
        <?php
        if(isset($seasonEnd))
        {
        ?>
            value="<?= $seasonEnd ?>" 
        <?php
        }
        ?>
        >

        <label id="descriptionLabel" for="description">Description :</label>  
        <textarea id="descriptionTextarea" name="description">
            <?php
            if(isset($description))
            {
            ?><?= $description; ?>
            <?php
            }
            ?>
            </textarea>

        <legend id="productAvailablityLegend" >Disponible :</legend>
        <span id="productAvailablity">

            <input type="radio" name="availablity" value="1"
            <?php
            if(isset($availablity) && $availablity)
            {
            ?>
                checked 
            <?php
            }
            ?>
            >
            <label for="availablity">oui</label>
            <input type="radio" name="availablity" value="0"
            <?php
            if(isset($availablity) && !$availablity)
            {
            ?>
                checked 
            <?php
            }
            ?>
            >
            <label for="availablity">non</label>
        </span>
        
        <legend id="productOfferLegend">Produit du moment :</legend>
        <span id="productOffer">
            <input type="radio" name="offer" value="1"
            <?php
            if(isset($offer) && $offer)
            {
            ?>
                checked 
            <?php
            }
            ?>
            >
            <label for="offer">oui</label>
            <input type="radio" name="offer" value="0"
            <?php
            if(isset($offer) && !$offer)
            {
            ?>
                checked 
            <?php
            }
            ?>
            >
            <label for="offer">non</label>
        </span>

        <label id="quantityAvailableLabel" for="quantityAvailable">Quantité dispo :</label>  
        <input id="quantityAvailableInput" type="number" name="quantityAvailable"
        <?php
        if(isset($quantityAvailable))
        {
        ?>
            value="<?= $quantityAvailable ?>" 
        <?php
        }
        ?>
        >

        <label id="unitsLabel" for="units">Unité de vente :</label>  
        <input id="unitsInput" type="text" name="units"
        <?php
        if(isset($units))
        {
        ?>
            value="<?= $units ?>" 
        <?php
        }
        ?>
        >

        <label id="priceLabel" for="price">Prix :</label>  
        <input id="priceInput" type="number" step="0.05" name="price"
        <?php
        if(isset($price))
        {
        ?>
            value="<?= $price ?>" 
        <?php
        }
        ?>
        >

    <?php
    if($data["action"] === "create")
    {
    ?>
        <button id="varietyFormButton" type"submit" name="varietyForm" value="create" >Créer</button>
    <?php
    }
    else if($data["action"] === "update")
    {
    ?>

        <button id="varietyFormButton" type"submit" name="varietyForm" value="update" >Modifier</button>
    <?php
    }
    else if($data["action"] === "delete")
    {
    ?>
        <button id="varietyFormButton" type"submit" name="varietyForm" value="delete" >Supprimer</button>
    <?php
    }
    ?>
    
        <input class="productMediaId" type="hidden" name="mediaId"
        <?php
        if(isset($mediaId) && $mediaId !== 0)
        {
        ?>
            value="<?= $mediaId ?>" 
        <?php
        }
        ?>
        >
    </form>

</main>