<main id="adminCrudNews">
    
    <?php require "_adminNav.phtml"; ?>

    <?php require "_messages.phtml"; ?>

    <?php
    if(isset($data["singleNews"]["news"]) && !empty($data["singleNews"]["news"]))
    {
        $id = $data["singleNews"]["news"]->getId();
        if(isset($id) && $id !== 0)
        {
            $newsId = $data["singleNews"]["news"]->getId();
        }
        else{
            $newsId = 0;
        }
        
        $newsCatId = $data["singleNews"]["news"]->getCategoryId();
        $newsName = $data["singleNews"]["news"]->getName();
        $newsMediaId = $data["singleNews"]["news"]->getMediaId();
        $newsContent = $data["singleNews"]["news"]->getContent();
    }
    
    if(isset($data["singleRecipe"]["recipe"]) && !empty($data["singleRecipe"]["recipe"]))
    {
        $id = $data["singleNews"]["news"]->getId();
        if(isset($id) && $id !== 0)
        {
            $newsId = $id;
        }
        else{
            $newsId = 0;
        }
        
        $newsCatId = $data["singleRecipe"]["recipe"]->getCategoryId();
        $newsName = $data["singleRecipe"]["recipe"]->getName();
        $newsMediaId = $data["singleRecipe"]["recipe"]->getMediaId();
        $newsContent = $data["singleRecipe"]["recipe"]->getContent();
        $recipeId = $data["singleRecipe"]["recipe"]->getRecipeId();
        $productId = $data["singleRecipe"]["recipe"]->getProductId();
        $ingredients = $data["singleRecipe"]["recipe"]->getIngredients();
        $steps = $data["singleRecipe"]["recipe"]->getSteps();
    }
    
    if($data["action"] === "createNews")
    {
    ?>
        <form id="adminNewsForm" method="POST" action="/Projet_Accou-ferme/adminCreateNews">
    <?php
    }
    else if($data["action"] === "createRecipe")
    {
    ?>
        <form id="adminNewsForm" method="POST" action="/Projet_Accou-ferme/adminCreateRecipe">
    <?php
    }    else if($data["action"] === "update")
    {
    ?>
        <form id="adminNewsForm" method="POST" action="/Projet_Accou-ferme/adminUpdateNews">
    <?php
    }
    else if($data["action"] === "delete")
    {
    ?>
        <form id="adminNewsForm" method="POST" action="/Projet_Accou-ferme/adminDeleteNews">
    <?php        
    }
    ?>
        <input type="hidden" name="id" 
        <?php
        if(isset($newsId))
        {
        ?>
            value="<?= $newsId ?>" 
        <?php
        }
        ?>
        >
        
        <input type="hidden" name="tokenAdminNews" 
        <?php
        if(isset($token))
        {
        ?>
            value="<?= $token ?>" 
        <?php
        }
        ?>
        >
        
        <input type="hidden" name="media_id" 
        <?php
        if(isset($newsMediaId))
        {
        ?>
            value="<?= $newsMediaId ?>" 
        <?php
        }
        ?>
        >

        <select id="selectNews" name="category_id">
            <option value="0">Selectionner une catégorie</option>

            <?php
            foreach($data["categories"] as $key => $category)
            {
            ?>
                <option value="<?= $category["id"]; ?>"
                <?php
                if((isset($newsCatId)) && $category["id"] === $newsCatId)
                {
                ?>
                    selected
                <?php
                }
                ?>
                > <?=$category["name"]; ?> </option>
            <?php
            }
            ?>
        </select>
        
        <label id="newsTitleLabel" for="name">Titre</label>  
        <input id="newsTitle" type="text" name="name" 
        <?php
        if(isset($newsName))
        {
        ?>
            value="<?= $newsName ?>" 
        <?php
        }
        ?>
        >

        <label id="newsContentLabel" for="content">Contenu</label>  
        <input id="newsContent" type="text" name="content"
        <?php
        if(isset($newsContent))
        {
        ?>
            value="<?= $newsContent ?>" 
        <?php
        }
        ?>
        >

        <?php
        if(isset($newsCatId) && $newsCatId === 3 || $data["action"] === "createRecipe")
        {
        ?>
        
        <select id="adminSelectProduct" name="product_id">
            <option value="0">Selectionner un produit</option>

            <?php
            foreach($data["allProducts"] as $key => $product)
            {
            ?>
                <option value="<?= $product["id"]; ?>"
                <?php
                if((isset($productId)) && $product["id"] === $productId)
                {
                ?>
                    selected
                <?php
                }
                ?>
                > <?=$product["name"]; ?> </option>
            <?php
            }
            ?>
        </select>
        
        <input type="hidden" name="recipeId"
        <?php
        if(isset($recipeId))
        {
        ?>
            value="<?= $recipeId ?>" 
        <?php
        }
        ?>
        >

        <label id="newsIngredientsLabel" for="ingredients">Ingrédients</label>  
        <input id="newsIngredients" type="text" name="ingredients"
        <?php
        if(isset($ingredients))
        {
        ?>
            value="<?= $ingredients ?>" 
        <?php
        }
        ?>
        >
        
        <label id="newsStepsLabel" for="steps">Etapes</label>  
        <input id="newsSteps" type="text" name="steps"
        <?php
        if(isset($steps))
        {
        ?>
            value="<?= $steps ?>" 
        <?php
        }
        ?>
        >
        
        <?php
        }
        ?>
        
    <?php
    if($data["action"] === "createNews")
    {
    ?>
        <button id="adminCrudNewsButton" type"submit" value="createNews" >Créer une actu</button>
    <?php
    }
    else if($data["action"] === "createRecipe")
    {
    ?>
        <button id="adminCrudNewsButton" type"submit" value="createRecipe" >Créer une recette</button>
    <?php
    }
    else if($data["action"] === "update")
    {
    ?>
        <button id="adminCrudNewsButton" type"submit" value="update" >Modifier</button>
    <?php
    }
    else if($data["action"] === "delete")
    {
    ?>
        <button class="button" id="adminCrudNewsButton" type"submit" value="delete" >Supprimer</button>
    <?php
    }
    ?>

    </form>

</main>