<main id="basket">
    
    <h1>Produits disponibles en ce moment</h1>
    
    <?php require "_messages.phtml"; ?>
    
    <section id="basketPreview" class="hideUpdate">
        <?php require "_update.phtml" ?>
    </section>

    <p class="validation">Après avoir cliqué sur "ajouter au panier", remontez sur la page pour voir le détail de votre
    panier</p>
    
    <section class="availableVarietySection">

		    <?php
            foreach($data['allAvailableVarieties'] as $key => $availableVariety)
            {
            ?>
            <article class="availableVariety card">
                <header class="availableVarietyHeader">
                    <h3> <?= $availableVariety["product_name"]; ?> </h3>
			    </header>
			    
			    <section class="availableVarietyMain">
                    
                    <?php
                    $medias = $data["medias"];
                    foreach($medias as $item)
                    {
                        if($item["availableVariety"]["id"] === $availableVariety["id"])
                        {
                            if(!is_null($item["media"]))
                            {
                            ?>
                            <figure class="availableVarietyFigure">
                                
                                <img src="<?= $item["media"]->getUrl(); ?>"
                                     alt="<?= $item["media"]->getAlt(); ?>">
                                     
                            </figure>
                            <?php
                            }
                            else
                            {
                               ?>
                                <figure class="availableVarietyFigure">
                                    
                                    <img src="./assets/img/varieties/panierVide.jpg"
                                         alt="Photo non disponible">
                                         
                                </figure>
                            <?php 
                            }
                        }
                    }
                    ?>
                    
			        <h3 class="availableVarietyTitle"><?= $availableVariety['name']; ?></h3>
			        
			        <p class="availableVarietyPrice">
                    <?= $availableVariety['price']; ?> €
				    <?php 
                    switch($availableVariety['units'])
                    {
                        case "kilo(s)":
                            echo "/ " . trim($availableVariety['units'], "(s)");
                            break;
                        case "pièce(s)":
                            echo "/ " . trim($availableVariety['units'], "(s)");
                            break;
                        case "botte(s)":
                            echo "/ " . trim($availableVariety['units'], "(s)");
                            break;
                    }
                    ?>
                    </p>
                    
                </section>
                <footer class="availableVarietyFooter">
                    
				    <form class="availableVarietyForm" method="POST" action="/Projet_Accou-ferme/basket-update">
				        <fieldset class="availableVarietyButton">
				            
				            <input id="variety-units-<?= $availableVariety["id"] ?>"
				                   type="hidden"
				                   name="availableVarietyUnits"
				                   value="<?=$availableVariety["units"]?>">
				                   
				            <input id="variety-price-<?= $availableVariety["id"] ?>"
				                   type="hidden"
				                   name="availableVarietyPrice"
				                   value="<?= $availableVariety["price"]?>">
				                   
				            <input id="variety-media-<?= $availableVariety["id"] ?>"
				                   type="hidden"
				                   name="availableVarietyMedia"
				                   value="<?= $availableVariety["media_id"]?>">

                            <button class="button buttonAddToBasket"
                                    type="submit"
                                    data-productAdded="<?= $availableVariety["name"]?>"
                                    data-product-id="<?= $availableVariety["id"] ?>"
                                    name="buttonAddToBasket"
                                    value="<?= $availableVariety["name"]?>">Ajouter au panier</button>
                            
                        </fieldset>
				    </form>
				    
				</footer>
			</article>
			<?php
            }
            ?>
            
    </section>
        
</main>