<aside class="update">
    
    <h2>Mon panier</h2>
    <ul>
        <li>
            <img class="basketImg" src="./assets/img/varieties/tomate-noire-de-crimee.jpg"></img>
            <h3 class="basketH3">Noire de Crimée</h3>
            <p class="basketP1">1 Kilo(s) 4 €</p>
            <p class="basketP2">4 €/Kilo</p>
        </li>

        <li>
            <img class="basketImg" src="./assets/img/varieties/panierVide.jpg"></img>
            <h3 class="basketH3">Choux-fleur</h3>
            <p class="basketP1">2 Pièce(s) 6 €</p>
            <p class="basketP2">3 € /Pièce</p>
        </li>
    </ul>
    
    <a href="">Continuer mes achats</a>
    <a href="">Voir mon panier</a>

</aside>