<main id="basket">
    
    <h1>Produits disponibles en ce moment</h1>
    
    <section id="basketPreview">
        <?php require "basket_update.phtml" ?>
    </section>
    
    <section class="availableVarietySection">

		    <?php
            foreach($data['allAvailableVarieties'] as $key => $availableVariety)
            {
            ?>
            <article class="availableVariety">
                <header class="availableVarietyHeader">
            
			        <?= $availableVariety["product_name"]; ?>
			        
			    </header>
			    
			    <main class="availableVarietyMain">
                    
                    <?php
                    $medias = $data["medias"];
                    foreach($medias as $item)
                    {
                        if($item["availableVariety"]["id"] === $availableVariety["id"])
                        {
                            if(!is_null($item["media"]))
                            {
                            ?>
                            <figure class="availableVarietyFigure">
                                <img src="<?= $item["media"]->getUrl(); ?>" alt="<?= $item["media"]->getAlt(); ?>" />
                            </figure>
                            <?php
                            }
                            else
                            {
                               ?>
                                <figure class="availableVarietyFigure">
                                    <img src="./assets/img/varieties/panierVide.jpg" alt="Photo non disponible" />
                                </figure>
                            <?php 
                            }
                        }
                    }
                    ?>
                    
			        <h3 class="availableVarietyTitle"><?= $availableVariety['name']; ?></h3>
                    
                </main>
                <footer class="availableVarietyFooter">
                    <p class="availableVarietyPrice">
                    <?= $availableVariety['price']; ?> €
				    <?php 
                    switch($availableVariety['units'])
                    {
                        case "kilo":
                            echo "/ " . $availableVariety['units'];
                            break;
                        case "pièce":
                            echo "/ " . $availableVariety['units'];
                            break;
                        case "botte":
                            echo "/ " . $availableVariety['units'];
                            break;
                    }
                    ?>
                    </p>
                    
				    <form class="availableVarietyForm" method="POST" action="/Projet_Accou-ferme/basket-update">
				        <fieldset class="availableVarietyButtonAdd">
				            <input id="variety-units-<?= $availableVariety["id"] ?>" type="hidden" name="availableVarietyUnits" value="<?=$availableVariety["units"]?>" />
				            <input id="variety-price-<?= $availableVariety["id"] ?>" type="hidden" name="availableVarietyPrice" value="<?= $availableVariety["price"]?>" />

                            <button type="submit" data-productAdded="<?= $availableVariety["name"]?>" data-product-id="<?= $availableVariety["id"] ?>" name="buttonAdd" class="buttonAdd" value="<?= $availableVariety["name"]?>">Ajouter au panier</button>
                        </fieldset>

				    </form>
				    
				</footer>
			</article>
			<?php
            }
            ?>
            
    </section>
        
</main>