<aside class="update">
    
    <h2>Mon panier</h2>
    <ul>
        <li>
            <img src=""></img>
            <h3>Noire de Crimée</h3>
            <p>1</p>
            <p>Kilo</p>
            <p>4 €</p>
        </li>
        <li>
            <img src=""></img>
            <h3>Choux-fleur</h3>
            <p>2</p>
            <p>Pièce</p>
            <p>6 €</p>
        </li>

    </ul>
    
    <a href="">Continuer mes achats</a>
    <a href="">Voir mon panier</a>

</aside>