<main id="basket">
    
    <h1>Produits disponibles en ce moment</h1>
    
    <section id="basketPreview">

    </section>
    
    <section class="availableVarietySection">

		    <?php
            foreach($data['allAvailableVarieties'] as $key => $availableVariety)
            {
            ?>
            <article class="availableVariety">
                <header class="availableVarietyHeader">
            
			        <?= $availableVariety["product_name"]; ?>
			        
			    </header>
			    
			    <main class="availableVarietyMain">
                    
                    <?php
                    $medias = $data["medias"];
                    foreach($medias as $item)
                    {
                        if($item["availableVariety"]["id"] === $availableVariety["id"])
                        {
                            if(!is_null($item["media"]))
                            {
                            ?>
                            <figure class="availableVarietyFigure">
                                <img src="<?= $item["media"]->getUrl(); ?>" alt="<?= $item["media"]->getAlt(); ?>" />
                            </figure>
                            <?php
                            }
                            else
                            {
                               ?>
                                <figure class="availableVarietyFigure">
                                    <img src="./assets/img/varieties/panierVide.jpg" alt="Photo non disponible" />
                                </figure>
                            <?php 
                            }
                        }
                    }
                    ?>
                    
			        <h3 class="availableVarietyTitle"><?= $availableVariety['name']; ?></h3>
                    
                </main>
                <footer class="availableVarietyFooter">
                    <p class="availableVarietyPrice">
                    <?= $availableVariety['price']; ?> €
				    <?php 
                    switch($availableVariety['units'])
                    {
                        case "kilo":
                            echo "/ " . $availableVariety['units'];
                            break;
                        case "pièce":
                            echo "/ " . $availableVariety['units'];
                            break;
                        case "botte":
                            echo "/ " . $availableVariety['units'];
                            break;
                    }
                    ?>
                    </p>
                    
				    <form class="availableVarietyButton" method="POST" action="/Projet_Accou-ferme/basket-update">
				        <fieldset class="availableVarietyName">
                            <input type="hidden" name="availableVarietyName" value="
                            <?= $availableVariety["id"] ?>
                            " />
                        </fieldset>
				        <fieldset class="availableVarietyButtonAdd">
                            <button type="submit" name="buttonAdd" id="buttonAdd">  +  </buton>
                        </fieldset>
				        <fieldset class="availableVarietyButtonRemove">
                            <button type="submit" name="buttonRemove" id="buttonRemove">  -  </buton>
                        </fieldset>
                        
				    </form>
				    
				</footer>
			</article>
			<?php
            }
            ?>
            
    </section>
        
</main>