<main id="contact">
    
    <h1>Contactez moi</h1>
    
    <p>Si vous avez une question, si vous désirez un renseignement, si vous voulez me faire une suggestion ou me transmettre une recette, n'hésitez pas!</p>
    
    <form id="contactForm" method="POST" action="/Projet_Accou-ferme/envoye">
        <fieldset id="contactFormInfo">
            <label id="contactFirstNameLab" for="first_name">Prénom : </label>
            <input id="contactFirstNameInp" type="text" name="first_name" />
            <label id="contactNameLab" for="name">Nom : </label>
            <input id="contactNameInp" type="text" name="name" />
            <label id="contactEmailLab" for="email">Email : </label>
            <input id="contactEmailInp" type="email" name="email" />
            <label id="contactTelLab" for="tel">Téléphone : </label>
            <input id="contactTelInp" type="tel" name="tel" />
        </fieldset>
        
        <fieldset id="contactFormText">
            <label id="contactMesLab" for="textarea">Entrez votre message :</label>
            <textarea id="contactText" type="textarea" name="message"></textarea>
        </fieldset>

        <fieldset id="contactFormSubmit">
            <button type="submit" class="button">Envoyer</button>
        </fieldset>
    </form>
    
</main>

