<main id="contact">
    
    <h1>Contactez moi</h1>
    
    <p>Si vous avez une question, si vous désirez un renseignement, si vous voulez me faire une suggestion ou me transmettre une recette, n'hésitez pas!</p>
    
    <?php
    
    if(isset($data["errors"]) && count($data["errors"]) > 0)
    {
    ?>
        <section class="errors">
            <ul>
                <?php
                foreach($data["errors"] as $key => $error)
                {
                ?>
                    <li> <?= $error ?></li>
                <?php
                }
                ?>
            </ul>
        </section>
    <?php
    }
    
    if(isset($data["validation"]) && count($data["validation"]) > 0)
    {
    ?>
        <section class="validation">
            <ul>
                <?php
                foreach($data["validation"] as $key => $valid)
                {
                ?>
                    <li> <?= $valid ?></li>
                <?php
                }
                ?>
            </ul>
        </section>
    <?php
    }
    ?>

    <form id="contactForm" method="POST" action="/Projet_Accou-ferme/envoye">
        <fieldset id="contactFormInfo">
            <label id="contactFirstNameLab" for="first_name">Prénom : </label>
            <input id="contactFirstNameInp" type="text" name="first_name" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?> 
                    value=" <?= $data["contact"]["first_name"] ?>"
                    <?php 
                }
                ?>
            />
            
            <label id="contactNameLab" for="name">Nom : </label>
            <input id="contactNameInp" type="text" name="name" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    value=" <?= $data["contact"]["name"] ?>"
                    <?php 
                }
                ?>
            />
            <label id="contactEmailLab" for="email">Email : </label>
            <input id="contactEmailInp" type="email" name="email" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    value=" <?= $data["contact"]["email"] ?>"
                    <?php 
                }
                ?>
            />            
            <label id="contactTelLab" for="tel">Téléphone : </label>
            <input id="contactTelInp" type="tel" name="tel" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    value=" <?= $data["contact"]["tel"] ?>"
                    <?php 
                }
                ?>
            />
            
        </fieldset>
        
        <fieldset id="contactFormText">
            <label id="contactMesLab" for="textarea">Entrez votre message :</label>
            <textarea id="contactText" type="textarea" name="message">
            <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    <?= $data["contact"]["message"] ?>"
                    <?php 
                }
                ?>
                </textarea>
        </fieldset>

        <fieldset id="contactFormSubmit">
            <button type="submit" class="button">Envoyer</button>
        </fieldset>
    </form>
    
</main>

