<section id="contact">
    
    <h1>Contactez moi</h1>
    
    <p>Si vous avez une question, si vous désirez un renseignement, si vous voulez me faire une suggestion ou me transmettre une recette, n'hésitez pas!</p>
    
    <?php require "_messages.phtml"; ?>
    
    <form id="contactForm" method="POST" action="/Projet_Accou-ferme/envoye">
        <fieldset id="contactFormInfo">
            
            <input id="contactToken" type="hidden" name="contactToken"
            <?php 
                if(isset($data["token"]))
                {
                    ?> 
                    value=" <?= $data["token"]; ?>"
                    <?php 
                }
                ?>
            > 
            
            <label id="contactFirstNameLab" for="contactFirstNameInp">Prénom : </label>
            <input id="contactFirstNameInp" type="text" name="first_name" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?> 
                    value=" <?= $data["contact"]["first_name"]; ?>"
                    <?php 
                }
                ?>
            >
            
            <label id="contactNameLab" for="contactNameInp">Nom : </label>
            <input id="contactNameInp" type="text" name="name" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    value=" <?= $data["contact"]["name"]; ?>"
                    <?php 
                }
                ?>
            >
            <label id="contactEmailLab" for="contactEmailInp">Email : </label>
            <input id="contactEmailInp" type="email" name="email" 
                <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    value=" <?= $data["contact"]["email"]; ?>"
                    <?php 
                }
                ?>
            >            
            <label id="contactTelLab" for="contactEmailInp">Téléphone : </label>
            <input id="contactTelInp" type="tel" name="tel" 
                <?php 
                if(isset($data["contact"]) && $data["contact"]["tel"] !== 0)
                {
                    ?>
                    value=" <?= $data["contact"]["tel"]; ?>"
                    <?php 
                }
                else
                {
                    ?>
                    value=""
                    <?php 
                }
                ?>
            >
            
        </fieldset>
        
        <fieldset id="contactFormText">
            <label id="contactMesLab" for="contactText">Entrez votre message :</label>
            <textarea id="contactText" name="message">
            <?php 
                if(isset($data["contact"]))
                {
                    ?>
                    <?= $data["contact"]["message"]; ?>
                    <?php 
                }
                ?>
                </textarea>
        </fieldset>

        <fieldset id="contactFormSubmit">
            <button type="submit" class="button">Envoyer</button>
        </fieldset>
    </form>
    
</section>

