<main class="mainGallery">
    
    <h1 id="mainGalleryTitle">Galerie Photos</h1>
    
    <section class="gallery">
        <img src="./assets/img/gallery/aubergine.jpg" alt="photo aubergines"></img>
        <img src="./assets/img/gallery/caisse.jpg" alt="photo caisse"></img>
        <img src="./assets/img/gallery/choux-fleur.jpg" alt="photo choux fleur"></img>
        <img src="./assets/img/gallery/concombres.jpg" alt="photo concombres"></img>
        <img src="./assets/img/gallery/legumes.jpg" alt="photo legumes"></img>
        <img src="./assets/img/gallery/poivrons.jpg" alt="photo poivrons"></img>
        <img src="./assets/img/gallery/semis.jpg" alt="photo semis"></img>
        <img src="./assets/img/gallery/tomates-min.jpg" alt="photo tomates"></img>
        <img src="./assets/img/gallery/tomates.jpg" alt="autre photo tomates"></img>
        <img src="./assets/img/recettes/aubergines-grillees.jpg" alt="photo aubergines grillees"></img>
        <img src="./assets/img/recettes/brochettes.jpg" alt="photo brochettes"></img>
        <img src="./assets/img/recettes/grill.jpg" alt="photo grill"></img>
    </section>

</main>