<main id="mainGallery">
    
    <h1>Galerie Photos</h1>
    
    <section id="gallery">
        
        <?php
        foreach($data["allMedias"] as $key => $media)
        {
        ?>
        <a href="<?= $media->getUrl(); ?>" target="_blank">
            <figure>
                <img src="<?= $media->getUrl(); ?>"
                     alt="<?= $media->getAlt(); ?>" />
            </figure>
        </a>
        <?php
        }
        ?>

    </section>

</main>

