<main id="home">
    
    <h1 id="main-title">Bienvenue chez Accou'ferme</h1>
    
        <section id="mainHome">
            <figure>
                <img src="./assets/img/logo-accouferme.png"
                     alt="logo Accouferme" />
            </figure>
        
                <article>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quidem, molestias at ut suscipit quaerat 
                    cupiditate dicta eveniet perferendis obcaecati neque repellat alias eaque inventore tempore minima 
                    quibusdam numquam est nemo quae quis tenetur repudiandae blanditiis rerum dolore provident ipsam in 
                    architecto ipsum id natus modi maxime laudantium aperiam ex possimus voluptatem quod consectetur 
                    necessitatibus qui nostrum!</p>
                    <p>Corporis magni voluptate cum similique qui distinctio libero blanditiis eum? 
                    Officia, maiores consequuntur numquam nemo sint. Repellendus, quae, cumque incidunt libero nam repellat 
                    quaerat pariatur culpa magnam nemo laboriosam unde quo laudantium eius autem in ipsum illum obcaecati velit
                    eveniet quisquam.</p>
                    <p>Impedit, odio tempora numquam consectetur. Magnam, dolore, dignissimos et minima nulla 
                    nam inventore.</p>
                </article>
    
        </section>
        
        <section id="homeProducts">
            
            
        </section>
        
        <section id="homeNews">
            
            
        </section>
        
        <section idhomeContact>
            
            <?php
            require "./templates/contact.phtml";
            ?>
            
        </section>
    
</main>