<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Accou'ferme</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jgthms/minireset.css@master/minireset.min.css">
    <link rel="stylesheet" href="./assets/css/style.css" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;700&display=swap" rel="stylesheet"> 
</head>
<body id="top">
    
<?php require "./templates/_header.phtml" ?>
	
<?php require "./templates/home.phtml" ?>

<?php require "./templates/_footer.phtml" ?>

</body>
</html>