<main id="legal">
    
    <h1>Mentions légales</h1>
    
    <p>Ce site est en cours, il est actuellement au stade d'exercice. Il est destiné à être mis en ligne mais pas
    avant quelques mois quand la personne, en cours de formation de maraîcher pour l'instant, s'installera.</p>
    
    <p>Les textes, faits rapidement pour l'execrice, vont être réécrits intégralement.</p>
    
    <p>Les images proviennent, pour la majorité d'entre elles, de banques d'images libres de droits. Elles aussi seront
    bien entendu toutes remplacées avant la mise en ligne</p>
    
    <p>Merci de votre attention, j'espère que cette visite vous a plu !</p>
    
</main>
