<section id="order">
    
    <h2>Passer commande</h2>
    
    <?php require "_messages.phtml"; ?>

    <section id="orderDetail">
        <form id="orderForm" action="/Projet_Accou-ferme/_validationOrder" method="POST">

            <?php 

            $orderVarieties = $data["order"];
            foreach($orderVarieties["items"] as $key => $orderVariety)
            {
            ?>
                
                <section class="orderVariety">
                    <h3 class="orderVarietyH3">Variété : <?= $orderVariety["variety"] ?></h3>

                    <p class="orderVarietyP1">prix <?= $orderVariety["price"] ?> €</p>

                    <p class="orderVarietyP2">par <?= trim($orderVariety["units"], "(s)") ?></p>

                    <p class="orderVarietyP3">Quantité : <?= $orderVariety["amount"] ?></p>

                    <p class="orderVarietyP4">soit : <?= ($orderVariety["totalVariety"]) ?> €</p>

                </section>
            <?php
            }
            if(isset($data["customer"]))
            {
                $customer = $data["customer"];
                
                $name = $customer["name"];
                $firstName = $customer["first_name"];
                $email = $customer["email"];
                $tel = $customer["tel"];
                $day = $customer["day"];
            }
            ?>

            <fieldset class="total">
                <a class="totalReturn button" href="commandes">Continuer mes achats</a>
                <p class="totalP">Prix total : <?= $orderVarieties["totalPrice"] ?> €</p>
                <input id="variety-totalPrice-<?= $orderVarieties["totalPrice"] ?>" type="hidden"
                       name="totalPrice"
                       value="<?= $orderVarieties["totalPrice"] ?>">
            </fieldset>
            <fieldset id="client">
                <label id="clientFirstNameLab" for="firstName">Entrez votre prénom</label>
                <input id="clientFirstNameIn" type="text" name="firstName" 
                <?php
                if(isset($firstName))
                {
                ?>
                    value="<?= $firstName ?>";
                <?php
                }
                ?>
                >
                <label id="clientNameLab" for="name">Entrez votre nom </label>
                <input id="clientNameIn" type="text" name="name" 
                <?php
                if(isset($name))
                {
                ?>
                    value="<?= $name ?>";
                <?php
                }
                ?>
                >
                <label id="clientEmailLab" for="email">Entrez votre Email </label>
                <input id="clientEmailIn" type="email" name="email"  
                <?php
                if(isset($email))
                {
                ?>
                    value="<?= $email ?>";
                <?php
                }
                ?>
                >
                <label id="clientTelLab" for="tel">Entrez votre numéro de téléphone </label>
                <input id="clientTelIn" type="tel" name="tel"  
                <?php
                if(isset($tel))
                {
                ?>
                    value="<?= $tel ?>";
                <?php
                }
                ?>
                >
            </fieldset>
            <fieldset id="retrait">
                <p id="retraitP">Choisissez le jour de retrait :</p>
                <input id="retraitMercIn" class="radio" type="radio" name="date_retrait" value="mardi"
                <?php
                if(isset($day) && $day === "mardi")
                {
                ?>
                    checked 
                <?php
                }
                ?>
                >
                <label id="retraitMercLab" for="mardi">Mardi</label>
                <input id="retraitMarIn" class="radio" type="radio" name="date_retrait" value="samedi"
                <?php
                if(isset($day) && $day === "samedi")
                {
                ?>
                    checked 
                <?php
                }
                ?>
                >
                <label id="retraitMarLab" for="samedi">Samedi</label>
            </fieldset>
            <fieldset id="orderSubmit">
                <input id="orderSubmitIn" class="button" type="submit" value="Valider la commande">
            </fieldset>
            
        </form>
        
        
    </section>